### ISSUE TITLE
The frontend asset for webpack-encore

### ISSUE THREAD

**Issue by paulZzhang** [gobuffalo/buffalo#1178]
The [webpack-encore](https://github.com/symfony/webpack-encore) is so easy than wepack.

Webpack Encore is a simpler way to integrate Webpack into your application. It wraps Webpack, giving you a clean & powerful API for bundling JavaScript modules, pre-processing CSS & JS and compiling and minifying assets. Encore gives you professional asset system that's a delight to use.

[Encore](https://github.com/symfony/webpack-encore) is inspired by [Webpacker ](https://github.com/rails/webpacker)and [Mix](https://laravel.com/docs/5.4/mix), but stays in the spirit of Webpack: using its features, concepts and naming conventions for a familiar feel. It aims to solve the most common Webpack use cases.

Can the framework replace webpack with webpack-encore?

**Comment by paulZzhang** [comment]
@markbates @stanislas-m #368

**Comment by markbates** [comment]
As said on https://github.com/gobuffalo/buffalo/issues/368#issuecomment-292991665 I still don't believe that using a different abstraction there is the right choice, especially since it's very easy to replace the details of `webpack.config.js` whatever the user would like to use. Using these sorts of specialized libraries is definitely what we have in mind for plugins.
