### ISSUE TITLE
Make install does not install pop

### ISSUE THREAD

**Issue by lukasschlueter** [gobuffalo/buffalo#1365]
## Steps to Reproduce the Problem

```bash
$ go get github.com/gobuffalo/buffalo
$ cd $GOPATH/src/github.com/gobuffalo/buffalo
$ git checkout tags/v0.13.0-rc.2 -b v0.13.0-rc.2
$ make install
```

## Expected Behavior

Running `buffalo db` or `buffalo pop` should be accessible and print usage information.

## Actual Behavior

```bash
$ buffalo db
ERRO[0001] Error: unknown command "db" for "buffalo"

Did you mean this?
        dev

$ buffalo pop
ERRO[0000] Error: unknown command "pop" for "buffalo"
```

## Info

<details>

```
### Buffalo Version
v0.13.0-rc.2

### App Information
Pwd=C:\Users\Lukas\go\bin
Root=C:\Users\Lukas\go\bin
GoPath=C:\Users\Lukas\go
Name=bin
Bin=bin\bin.exe
PackagePkg=../bin
ActionsPkg=../bin/actions
ModelsPkg=../bin/models
GriftsPkg=../bin/grifts
VCS=
WithPop=false
WithSQLite=false
WithDep=false
WithWebpack=false
WithYarn=false
WithDocker=false
WithGrifts=false
WithModules=false

### Go Version
go version go1.11 windows/amd64

### Go Env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Lukas\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Lukas\go
set GOPROXY=
set GORACE=
set GOROOT=D:\Programs\Go
set GOTMPDIR=
set GOTOOLDIR=D:\Programs\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Lukas\AppData\Local\Temp\go-build445136518=/tmp/go-build -gno-record-gcc-switches

### Node Version
v8.11.1

### NPM Version
5.6.0

### Yarn Version
1.9.4

### PostgreSQL Version
PostgreSQL Not Found

### MySQL Version
MySQL Not Found

### SQLite Version
3.24.0 2018-06-04 19:24:41 c7ee0833225bfd8c5ec2f9bf62b97c4e04d03bd9566366d5221ac8fb199a87ca

### Dep Version
could not find a Gopkg.toml file

### Dep Status
could not find a Gopkg.toml file
```

</details>

**Comment by markbates** [comment]
It’s a make install command for Buffalo, not the whole eco-system. This is a command for people working on the buffalo binary, not for end users to install the complete eco-system.

Running buffalo new should install all deps for a new app, including pop.

Thanks.

-----------
Mark Bates

**Comment by EssenceOfChaos** [comment]
I'm having the same issue but after using `buffalo new`.
I ran `buffalo db create -a` which worked.
Then `buffalo dev` produced `ERRO[0001] [PLUGIN] error loading plugin /path/to/app/buffalo-pop: signal: killed` but still booted the app.
Trying to create a resource like `buffalo g resource users` results in:
```
 create  locales/users.en-us.yaml
      create  templates/users/_form.html
      create  templates/users/edit.html
      create  templates/users/new.html
      create  templates/users/show.html
      create  actions/users_test.go
      create  templates/users/index.html
      create  actions/users.go
         run  buffalo db g model user
ERRO[0001] [PLUGIN] error loading plugin /path/to/app/buffalo-pop: signal: killed

ERRO[0001] Error: unknown command "db" for "buffalo"

Did you mean this?
        dev
```
The model and migration aren't created, even though the postgres server is running and the DB is created. Since it created the actions/users.go it's now referencing an undefined `models.User`

This is my first time working witih buffalo. I installed via homebrew

**Comment by markbates** [comment]
You need to provide the output buffalo new. Since it didn’t correctly install the plug-in, the output should give you, and those I, info on why.

Thanks.

-----------
Mark Bates

**Comment by fdonzello** [comment]
I have the same error.
Running `/go/bin/buffalo-pop` directly works fine. But `buffalo pop` does not.

Error:

> ERRO[0006] [PLUGIN] error loading plugin /go/bin/buffalo-pop: signal: killed 
> ERRO[0006] Pop support has been moved to the https://github.com/gobuffalo/buffalo-pop plugin.
> 
> !! PLEASE READ PLUGIN DOCUMENTATION - https://gobuffalo.io/en/docs/plugins
> 
> Buffalo Plugins Installation*:
> 
>         $ buffalo plugins install github.com/gobuffalo/buffalo-pop
> 

If I run `buffalo plugins install github.com/gobuffalo/buffalo-pop`:

> ERRO[0005] [PLUGIN] error loading plugin /go/bin/buffalo-pop: signal: killed

**Comment by dlifanov** [comment]
Same issue

**Comment by lpar** [comment]
For those still getting the `ERRO[0005] [PLUGIN] error loading plugin /go/bin/buffalo-pop: signal: killed` bug, a couple of things to try:

Turns out the default context timeout for plugin binaries is only 2 seconds, and that's not enough to run a plugin install, or the buffalo-pop plugin in many cases. Try setting `BUFFALO_PLUGIN_TIMEOUT` environment variable to something like `10s` or even `30s`.

Another thing to check is that your `config/buffalo-pop.toml` file isn't corrupted in some way, that can also cause the same error.
