### ISSUE TITLE
Authboss integration almost done, just some troubles. Any hint?

### ISSUE THREAD

**Issue by frederikhors** [gobuffalo/buffalo#1503]
@markbates told me (https://github.com/volatiletech/authboss/issues/163) that he does not use `authboss` and so for now he can not spend time integrating it with `buffalo`.

I'm opening this in case him or maybe @paganotoni, @stanislas-m or someone else can **understand in a moment** what is wrong with this: https://github.com/frederikhors/buffalo-authboss-sample

**Stackoverflow question**: https://stackoverflow.com/questions/53742344/gobuffalo-and-authboss-authentication-system-integration

I think I'm almost there, just something wrong, I don't understand what.

**Comment by lukasschlueter** [comment]
The 404 error code you received is not a buffalo error, it's comming from authboss.

When I try to open `127.0.0.1:3000/auth/authboss/login`, authboss redirects to `http://127.0.0.1:3000/boss/login/` which is generating a buffalo 404 error as that route has not been mapped. 

It appears to me you are missing some important configuration for authboss.
Authboss is running, but it's not where you expected it to be.

I'm not familiar with authboss at all so I can't really tell you how to fix this problem.
Maybe someone from the authboss community can help you with that?

As a personal side note: 
I saw you opening quite a lot of issues and comments on various repos (and SO). While I can understand that this problem is bugging you, I don't think this is a good approach.

**Comment by frederikhors** [comment]
@lukasschlueter thanks for your answer and your opinion.

`127.0.0.1:3000/auth/authboss/login` is **NOT** the right link: `127.0.0.1:3000/auth/login` **IS**: still `404 page not found`, but maybe you can understand why.

> I saw you opening quite a lot of issues and comments on various repos (and SO). While I can understand that this problem is bugging you, I don't think this is a good approach.

I opened this issue and one on `authboss` repo. And a SO question.
What do you suggest to do? I'm trying and re-trying but I can't understand what is wrong.
**Expert people like you** can help and I created a repo for this reason, to facilitate:  https://github.com/frederikhors/buffalo-authboss-sample.

I think both `buffalo` and `authboss` can grow together to lead Go's world (like Rails and devise).

If I'm wrong, I apologize.

_Can you help?_

**Comment by lukasschlueter** [comment]
As I said before, I'm not familiar with authboss so I can't tell you, what exactly causes this issue.

I can tell that buffalo is mounting authboss and authboss is actually reachable (else it wouldn't be redirecting). But that's were my knowledge ends.

**Comment by frederikhors** [comment]
Can you reopen the issue as someone can help us?
