### ISSUE TITLE
Do not generate "/edit" route during API generation

### ISSUE THREAD

**Issue by hubyhuby** [gobuffalo/buffalo#1562]
## Description
When generating a project with "--api" you get a route an /edit route for each ressource.
While this make sens for HTML-default mode (without --api), in API mode this doesn t seem to be logical.
In HTML mode the edit route pulls the form with the previous recorded datas to midify.
Then the form will "PUT" the data to update this record.
With API mode you usally handle this "edit" part on your front end and then call directely the PUT / Update API route.

Example of routes : 

GET    | /chats                                |         | chatsPath            | generatedApps/tst2/actions.ChatsResource.List
POST   | /chats                                |         | chatsPath            | generatedApps/tst2/actions.ChatsResource.Create
GET    | /chats/new                            |         | newChatsPath         | generatedApps/tst2/actions.ChatsResource.New
PUT    | /chats/{chat_id}                      |         | chatPath             | generatedApps/tst2/actions.ChatsResource.Update
DELETE | /chats/{chat_id}                      |         | chatPath             | generatedApps/tst2/actions.ChatsResource.Destroy
GET    | /chats/{chat_id}                      |         | chatPath             | generatedApps/tst2/actions.ChatsResource.Show
GET    | /chats/{chat_id}/edit                 |         | editChatPath         | generatedApps/tst2/actions.ChatsResource.Edit

### Expected Behavior

In API mode the "/Edit" route is not required, and shall not be produced. Limitating the surface of the API.

### Buffalo Version
v0.12.4
### Go Version
go version go1.10.4 linux/amd64

**Comment by markbates** [comment]
This isn't as straightforward as it appears. It could introduce breaking changes and will need to be investigated further.

The `Resource` interface currently requires both `New` and `Edit` functions. The `BaseResource` provides no-op implementations of all of the `Resource` methods. The router then builds routes for each of the methods in the interface.

So in order to *not* generate routes for `Edit` and `New` we would need to make considerable changes to the `Resource` interface, the `BaseResource` type, and the router.

I'm not saying this can't be done, but it requires a decent amount of thought and planning before it can be implemented, as it has the potential to be a breaking change.

I consider this to be out of scope for the `v0.14.0` release, but could, potentially, be included in a `v0.15` release.

**Comment by markbates** [comment]
Fixed in `v0.14.1` (not released yet)

**Comment by hubyhuby** [comment]
Hi Mark,
Thank you for including it already in the next release !
I was away for some days, I thought there would have been some discussions in this thread before the release.
If you agree it is logical to remove "/edit" in api mod, that s cool.
Have a nice day
