### ISSUE TITLE
Application singleton is not really a singleton.

### ISSUE THREAD

**Issue by twisted1919** [gobuffalo/buffalo#1653]
## Description

It seems that the application singleton is not really a singleton, or something weird happens with my app.   

If you take a look at:
<img width="1123" alt="Screenshot 2019-04-19 20 18 21" src="https://user-images.githubusercontent.com/957490/56435234-6fd5f500-62e0-11e9-8798-49227c9bafda.png">
you will see how some of my routes are registered twice.  
I have a hunch this happens because in my app, i am also running a udp server, and inside it i defined a logger function like: 
```
func logger() buffalo.Logger {
	return actions.App().Options.Logger
}
``` 
And i guess this somehow affects what's going on. It's just a hunch though.  

However, if instead of:
```
    func App() *buffalo.App {
        if app == nil { ... }
    }
```

i'm using `sync.Once`:
```
    var appOnce sync.Once
    func App() *buffalo.App {
        appOnce.Do(func() {  ...  })
    }
```

Then my issue goes away, no more duplicate routes.  

### Steps to Reproduce the Problem

  See above.

### Expected Behavior

I expect to see unique routes.

### Actual Behavior

I see duplicate routes

**Comment by sio4** [comment]
Indeed, this issue (`action.App()` is called multiple times while `app` is still `nil`) could very rarely happen since we don't use any locking method such as `sync.Once` on our scaffold. Also, `App` itself is not a singleton from the perspective of the core library, but it could be or have to be from the perspective of the user application.

However, it will not happen frequently (actually not happen in most case) since our scaffold also has `init()` function calling `actions.App()` in `grifts/init.go` before `main()` is executed. (this example [1] too) In this case, the variable `actions.app` will not be `nil` when `actions.App()` is called from other places including the `main()` of the app, but yes, it is not guaranteed when the app is somewhat complex.

But I am not sure how it happened... if the user-defined `logger()` which calls `App()` is called... from where and when...

I think we can improve the scaffolded `app.go` with `Sync` but still, this is a user's domain.

[1] http://gobuffalo.io/documentation/guides/goth/#example-usage

**Comment by fasmat** [comment]
> Indeed, this issue (`action.App()` is called multiple times while `app` is still `nil`) could very rarely happen since we don't use any locking method such as `sync.Once` on our scaffold. Also, `App` itself is not a singleton from the perspective of the core library, but it could be or have to be from the perspective of the user application.
> 
> However, it will not happen frequently (actually not happen in most case) since our scaffold also has `init()` function calling `actions.App()` in `grifts/init.go` before `main()` is executed. (this example [1] too) In this case, the variable `actions.app` will not be `nil` when `actions.App()` is called from other places including the `main()` of the app, but yes, it is not guaranteed when the app is somewhat complex.
> 
> But I am not sure how it happened... if the user-defined `logger()` which calls `App()` is called... from where and when...
> 
> I think we can improve the scaffolded `app.go` with `Sync` but still, this is a user's domain.
> 
> [1] http://gobuffalo.io/documentation/guides/goth/#example-usage

We should still make sure that the code generated with `buffalo new` doesn't contain any possible race conditions that should be fixed by the users.

The generated `actions.App()` function is not safe to be called from multiple goroutines, but it should be imho. It's also a straight forward fix: wrap the initialization of `app` with a `sync.Once`. I just haven't had time yet to update the necessary templates in the gobuffalo cli and write a fixer for it.

**Comment by sio4** [comment]
> We should still make sure that the code generated with `buffalo new` doesn't contain any possible race conditions that should be fixed by the users.
> 
> The generated `actions.App()` function is not safe to be called from multiple goroutines, but it should be imho. It's also a straight forward fix: wrap the initialization of `app` with a `sync.Once`.

Yeah, I fully agree. Having a possible bug in the generated code for the user is not a good thing. I think adding that sync could be fine.

Also, at the same time, I am curious about what made this very edge case happen. As described above, `grifts/init.go` could be the first caller of the function, and this stage, when `init()` invoking, I don't think goroutines starting... :thinking: 
(Issue is too old to ask the situation... )
