### ISSUE TITLE
[help] switch FROM clause by request parameter 

### ISSUE THREAD

**Issue by ROhta** [gobuffalo/buffalo#1745]
## Description
How can I switch destination tables according to request parameter?
In SQL, I want to switch FROM clause by request parameter value of application.

- DB has many tables of same schema.
- These tables are created by another application, so this application doesn't know what tables there are.
- Request parameter specifies table name.
    - ex. https://domain/?table_name=bananaOne
- If a request is below, I think I have to staticly define the bananaTwo struct, otherwise Buffalo do not connect the bananaTwo table.
    - ex. https://domain/?table_name=bananaTwo
- I made a model ↓ with static struct, but I couldn't find way to define with  struct dynamically.

### Info.
```
type BananaOne struct {
    ID             int    `db:"id"    rw:"r"`
    bananaType string `db:"banana_type"`
    banana        string `db:"banana"`
    farmerID       int    `db:"editor_id"`
}
func (s *BananaOne) GetBanana(tx *pop.Connection, bananaType string) ([]string, error) {
    var ss []*BananaOne
    err := tx.Where("banana_type = ?", bananaType).All(&ss)
    var bananas []string
    for _, s := range ss {
        bananas = append(bananas, s.banana)
    }
    return bananas, err
}
```

</details>

**Comment by stanislas-m** [comment]
Hello! If you have any question, please consider using the Slack channel (#buffalo, #buffalo_fr or #buffalo-dev for contribution related questions) or Stack Overflow. We use GitHub issues for bug reports and feature requests only.

Otherwise, the only solution to do what you want is to create all the expected versions of the struct you can have, and test for the correct one to use. Buffalo / pop won't help on that, and allowing such dynamic thing is really dangerous.
