### ISSUE TITLE
Does not run on netbsd

### ISSUE THREAD

**Issue by devosalain** [gobuffalo/buffalo#1760]
buffalo new bloggy 
,produces
DEBU[2019-03-24T12:50:31+01:00] Exec: go get -t ./...
grifts/init.go:5:2: cannot find package "../../mysrc/bloggy/actions" in:
        /home/x/go/mysrc/mysrc/bloggy/actions

**Comment by markbates** [comment]
Your problem is most likely environmental. https://gobuffalo.io/en/docs/gomods

You didn't fill out the information requested so people can properly help you. I'm closing this ticket as it's most likely environmental, but since the ticket is lacking the necessary details, we can't be sure.

If the issue persists, please open the ticket again with the necessary information for people to help you.
