### ISSUE TITLE
Cannot bind twice http request (JSON format)

### ISSUE THREAD

**Issue by sebd71** [gobuffalo/buffalo#1844]
## Description

Call multiples time c.Bind with "application/json" or "application/xml" binder type is not working due to the fact that req.body can only be read one time.

### Steps to Reproduce the Problem

Following test illustrates the problem :
```
package binding_test

import (
	"encoding/json"
	"net/http"
	"testing"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/buffalo/render"
	"github.com/gobuffalo/httptest"
	"github.com/stretchr/testify/require"
)

func Test_BindTwiceJSON(t *testing.T) {
	r := require.New(t)

	render := render.New(render.Options{
		DefaultContentType: "application/json",
	})

	type U struct {
		F string
	}
	app := buffalo.New(buffalo.Options{})
	app.POST("/", func(c buffalo.Context) error {
		var ux, uy U
		// Bind once
		if err := c.Bind(&ux); err != nil {
			return c.Render(http.StatusInternalServerError, render.String(err.Error()))
		}
		// Bind twice
		if err := c.Bind(&uy); err != nil {
			return c.Render(http.StatusInternalServerError, render.String(err.Error()))
		}
		return c.Render(http.StatusOK, render.JSON(U{
			F: "ux=" + ux.F + ", uy=" + uy.F + " OK",
		}))
	})

	w := httptest.New(app)
	res := w.JSON("/").Post(&U{F: "foo"})

	r.Equal(http.StatusOK, res.Code, "Http code not OK, body='%v'", res.Body)

	var resVal U
	r.NoError(json.Unmarshal(res.Body.Bytes(), &resVal))
	r.Equal("ux=foo, uy=foo OK", resVal.F)
}
```

Just create a new file (for example: binding/binding_bind_json_test.go) in buffalo repo and run tests (`make test -m Test_BindTwiceJSON`)
You will get the following error : 
```
--- FAIL: Test_BindTwiceJSON (0.07s)
    binding_bind_json_test.go:43: 
                Error Trace:    binding_bind_json_test.go:43
                Error:          Not equal: 
                                expected: 200
                                actual  : 500
                Test:           Test_BindTwiceJSON
                Messages:       Http code not OK, body='EOF'
```

I will post soon a fix proposal based on packd. 
My fix is very similar to what you've done in #1480.

**Comment by sebd71** [comment]
Pull request posted : https://github.com/gobuffalo/buffalo/pull/1846

**Comment by alejandrombc** [comment]
This is still happening in 2022

**Comment by fasmat** [comment]
I don't see why this is supposedly a bug that needs fixing?

Bind is only intended to be called once per request, since it reads the request body (which can only be read once via an `io.Reader` interface).

The linked PR doesn't actually solve the stated problem. It creates an in memory file with the contents of the request just for it to be able to be read twice. There are 2 problems with that:

1. This causes extra memory to be allocated for a possible second read of the request body. This will cause performance issues for the off chance that some controller wants to call `c.Bind` twice
2. Every request writes to the same in memory file. This is not concurrency safe! Between wrapping the request body as in memory file and parsing this file as json or xml a different request can overwrite the contents of the file!

Since the originally stated "bug" is intentional behavior and the intended "fix" introduces problems that were not addressed by the author no progress has been made on this topic and the issue was closed eventually.
