### ISSUE TITLE
go 1.18 support

### ISSUE THREAD

**Issue by dengqinghua** [gobuffalo/buffalo#2227]
Hi there

As the 1.18 version released, and the support of generic is important for our rapid development.

But I've checked the latest buffalo, only support the 1.17 version.

Any roadmap for this 1.18 support?

Many thanks if we could use the generic thing, we could use stream like Java8 did.

**Comment by sio4** [comment]
Hi, thanks for the question.
As you said, the current version of buffalo supports go versions 1.16 and 1.17. Since our direction is supporting the last two versions of golang, it could be better if we can move forward. However, I am not fully sure it could be in the near future since we are currently working on planning the next step, buffalo v1, and in my opinion, we need to focus on the new plan. This is not the team's decision for now but I would like to tell it to let you know the project's status.

Anyways, even though we officially do not support go 1.18, I guess most of the things will work well on the new version without framework level change and you may be able to use the new feature of 1.18 in your own code.

**Comment by sio4** [comment]
Hi @dengqinghua 

Good news on your question! I am currently working on shifting the supported versions of go, and it seems like we are close to the goal. (All the package level tests and integration tests were successful, also the result of some manual tests was also good.)

Thank you for your interest and support!
