### ISSUE TITLE
v0.18.5 is not tagged in Docker Hub

### ISSUE THREAD

**Issue by jamtur01** [gobuffalo/buffalo#2231]
```
Sending build context to Docker daemon  575.5kBStep 1/20 : FROM gobuffalo/buffalo:v0.18.5 as builder
manifest for gobuffalo/buffalo:v0.18.5 not found
```

Thanks!

**Comment by sio4** [comment]
The latest version of the docker image is v1.18.3. It's a little tricky, this package, gobuffalo/buffalo, is the core library for the buffalo apps while the separated package gobuffalo/cli provides `buffalo` cli. The docker image follows the version of the `buffalo` cli since the image is basically for development.

**Comment by fasmat** [comment]
To add to what @sio4 said:

The reason that the newest docker image is versioned according to the CLI at version `v0.18.3` is because that's the only thing that is included in the image. The `gobuffalo/buffalo` library isn't included in the docker image, it is referenced by your `go.mod` file and is fetched during the build process.

So if you want to use the newest `gobuffalo/buffalo` library you can just call:

```bash
go get github.com/gobuffalo/buffalo
go mod tidy       # optional to remove unneeded dependencies from your go.mod and go.sum files
```

and commit the changes to your repository.
