### ISSUE TITLE
Create a Docker container to run Buffalo

### ISSUE THREAD

**Issue by rabellamy** [gobuffalo/buffalo#250]
Based on a [discussion in slack](https://gophers.slack.com/archives/buffalo/p1487166662001013) it has come to light that a few members of the community need to run a Buffalo build inside a Docker container. 

- [ ] Choose a [base image](https://hub.docker.com/_/golang/)
- [ ] Determine where the Buffalo artifact should be built (inside the container or on the host machine)
- [ ] Create a Makefile
- [ ] Outline some resources/examples for deploying the container with `Docker Compose` and `
Kubernetes`

**Comment by drlogout** [comment]
I tried to run a cross compiled binary in a docker container with no success. I got always an error from go.rice:

```
panic: could not locate box "../public/assets"
```

First I cross compiled the app:
```
$ GOOS=linux GOARCH=amd64 buffalo build
```

Then I added the binary and also the public directory in the `Dockerfile`:

```
$ docker run -it buffalo-app ls -l /app/
total 8
drwxr-xr-x    1 root     root          4096 Feb 15 13:46 bin
drwxr-xr-x    3 root     root          4096 Feb 15 13:46 public
```

If I compile the app for macOS and run the binary (somewhere) on macOS it works perfect.

**Comment by drlogout** [comment]
I tried a different approach, not that elegant, but working:

```Dockerfile
FROM golang:1.7.5

RUN go get -u github.com/gobuffalo/buffalo/buffalo

RUN curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh && \
    bash nodesource_setup.sh && \
    apt-get install -y nodejs build-essential

ADD . /go/src/github.org/drlogout/a-buffalo-app
RUN rm -rf /go/src/github.org/drlogout/a-buffalo-app/node_modules

WORKDIR /go/src/github.org/drlogout/a-buffalo-app

RUN npm install
RUN buffalo build -o bin/app

CMD ["/go/src/github.org/drlogout/a-buffalo-app/bin/app"]
```

**Comment by apaganobeleno** [comment]
I've seen this issue in a different context, when i first share a buffalo project with a team-mate he has to manually create the /public/assets directory in order to be able to run the project.

Perhaps this issue you're facing is because the /public/assets folder is inside the generated `.gitignore` could you try adding it on your dockerfile ? p.e. `RUN mkdir -p public/assets` before `RUN buffalo build...` command ?

**Comment by markbates** [comment]
@drlogout that's not an "inelegant" solution, that is in fact, how you should be doing it. 

After getting more insight from this ticket, it would appear that the actual problem is not with `rice`, but rather with expectations, documentation, and perhaps error messaging.

When building a "standard" buffalo application you need to have all of the tools necessary to build it, that includes Go, Node, NPM, and the installed NPM modules, which is exactly what @drlogout is doing in his Dockerfile, and exactly what is happening in the [Dockerfile](https://github.com/gobuffalo/buffalo/blob/master/Dockerfile) we use to test Buffalo apps. 

I was never able to recreate this issue, or even understand it, until this ticket, and in particular seeing how @drlogout solved the problem.

So, knowing what we now know, which is the tools need to be installed in order to build an application, what is the next steps to "fixing" this issue?

**Comment by bketelsen** [comment]
for me, i was already building with a dockerfile that had node and Go, so the problem was likely that public/assets didn't exist. I'll test this.

**Comment by apaganobeleno** [comment]
Maybe building a base docker image that has all the tools installed (NPM, Go, Node) could also help the buffalo tests by skipping that installation in our Dockerfile and serve as base for builds that need to happen inside a container.

**Comment by markbates** [comment]
@apaganobeleno yes, as long as it doesn't actually contain any Buffalo code, since the `Dockerfile` in the Buffalo repo is used to test locally developed code.

What I would love is proper Docker images for each Buffalo release.

`FROM buffalo:0.7.3`

It would have Go, Node, NPM, and all of the Buffalo code and dependencies from that particular release already installed on it. We could automate that in the https://github.com/gobuffalo/buffalo/blob/master/grifts%2Frelease.go task so it would automatically get built and released when we do new releases. That's the ideal, for me, at least.

**Comment by markbates** [comment]
Now, who wants to own building those images? :)

**Comment by bketelsen** [comment]
I’m already half there, I’ll take it on.

**Comment by bketelsen** [comment]
BTW, just creating the public/assets directory fixed it for me in docker!

BK

**Comment by rabellamy** [comment]
@drlogout: I tried to build a modified version of your [Dockerfile](https://github.com/gobuffalo/buffalo/issues/250#issuecomment-280027652), essentially personalizing the app path.

```dockerfile
FROM golang:1.7.5

RUN go get -u github.com/gobuffalo/buffalo/buffalo

RUN curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh && \
    bash nodesource_setup.sh && \
    apt-get install -y nodejs build-essential

ADD . /go/src/github.org/rabellamy/example-web-app
RUN rm -rf /go/src/github.org/rabellamy/example-web-app/node_modules

WORKDIR /go/src/github.org/rabellamy/example-web-app

RUN npm install
RUN buffalo build -o bin/app

CMD ["/go/src/github.org/rabellamy/example-web-app/bin/app"]
```

My build is failing on `RUN buffalo build -o bin/app` with these errors:
```bash
 ---> f85ac3645d31
Removing intermediate container 717e768b3111
Step 8/9 : RUN buffalo build -o bin/app
 ---> Running in ca83bf07b4da
Buffalo version 0.7.3

--> cleaning up target dir
--> running node_modules/.bin/webpack
Hash: 2fd85d12eca92ab76aab
Version: webpack 1.14.0
Time: 3566ms

                                 Asset     Size  Chunks             Chunk Names                                                                                             [35/1945]
af7ae505a9eed503f8b8e6982036873e.woff2  77.2 kB          [emitted]
  f4769f9bdb7466be65088239c12046d1.eot  20.1 kB          [emitted]
 fa2772327f55d8198301fdb8bcfc8158.woff  23.4 kB          [emitted]
  e18bbf611f2a2e43afc071aa2f4e1512.ttf  45.4 kB          [emitted]
  89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]
  674f50d287a8c48dc19ba404d20fe713.eot   166 kB          [emitted]
448c34a56d699c29117adc64c43affeb.woff2    18 kB          [emitted]
 fee66e712a8a08eef5805a46892932ad.woff    98 kB          [emitted]
  b06871f281fee6b241d60582ae9369b9.ttf   166 kB          [emitted]
  912ec66d7572ff821749319396470bde.svg   444 kB          [emitted]
                        application.js   372 kB       0  [emitted]  main
                       application.css   183 kB       0  [emitted]  main
                       images/logo.svg    66 kB          [emitted]
   [0] multi main 52 bytes {0} [built]
    + 21 hidden modules
Child extract-text-webpack-plugin:
        + 15 hidden modules
--> running go build -v -o bin/app -ldflags -X main.version="2017-02-20T02:33:36Z" -X main.buildTime="2017-02-20T02:33:36Z"                                                 [17/1945]
buffalo_build_main.go:11:2: cannot find package "github.com/GeertJohan/go.rice" in any of:
        /usr/local/go/src/github.com/GeertJohan/go.rice (from $GOROOT)
        /go/src/github.com/GeertJohan/go.rice (from $GOPATH)
buffalo_build_main.go:10:2: cannot find package "github.com/markbates/grift/grift" in any of:
        /usr/local/go/src/github.com/markbates/grift/grift (from $GOROOT)
        /go/src/github.com/markbates/grift/grift (from $GOPATH)
grifts/routes.go:7:2: cannot find package "github.com/olekukonko/tablewriter" in any of:
        /usr/local/go/src/github.com/olekukonko/tablewriter (from $GOROOT)
        /go/src/github.com/olekukonko/tablewriter (from $GOPATH)
main.go:10:2: cannot find package "github.com/rabellamy/example-web-app/src/actions" in any of:
        /usr/local/go/src/github.com/rabellamy/example-web-app/src/actions (from $GOROOT)
        /go/src/github.com/rabellamy/example-web-app/src/actions (from $GOPATH)
--> cleaning up build
----> cleaning up buffalo_build_main.go
----> cleaning up a
----> cleaning up a/a.go
----> cleaning up a/database.go
----> cleaning up buffalo_build_main.go
Error: exit status 1

Usage:
  buffalo build [flags]

Aliases:
  build, b, bill


Flags:
  -e, --extract-assets   extract the assets and put them in a distinct archive
  -o, --output string    set the name of the binary (default "bin/example-web-app")
  -z, --zip              zips the assets to the binary, this requires zip installed
```

What is the output for `go env` inside your resulting container?

@bketelsen: Which base image are you using?

**Comment by markbates** [comment]
@rabellamy try looking at the dockerfile we uss to test Buffalo see if that has any guidance.

**Comment by drlogout** [comment]
Your go dependencies are not installed.
It worked in my case, because I have a vendor directory in my project folder.

**Comment by jgeiger** [comment]
Something to consider, if you're going to try to run it in development mode, you're going to need to include the binary commands for all of the dbs beyond just sqlite.

I looked at your testing [Dockerfile](https://github.com/gobuffalo/buffalo/blob/master/Dockerfile) and doesn't take those into account.

I have a similar setup in Rails where all the rake commands are run via the same container as
```
docker-compose run app command
```

**Comment by markbates** [comment]
https://github.com/gobuffalo/buffalo/pull/405/files#diff-d92c0cc6cc3b84dda3c92547bcf56981

**Comment by jayunit100** [comment]
`RUN mkdir -p public/assets` @msenmurugan
