### ISSUE TITLE
Add basic functions into the default implementation of resource functions

### ISSUE THREAD

**Issue by as27** [gobuffalo/buffalo#297]
The generator for resources should generate some more code into the default implementations. The command `buffalo g r users` should add a basic functionality for the model `user`. 

The generated code should be similar like in the [html-resource example](https://github.com/gobuffalo/buffalo/blob/master/examples/html-resource/actions/users.go). But I would suggest not to use a middleware inside the generated code, because of readability issues.

**Comment by markbates** [comment]
It'll be cleaner if you use the new(ish) ValidateAnd... methods https://godoc.org/github.com/markbates/pop#Connection.ValidateAndCreate

**Comment by markbates** [comment]
This probably better code to model after https://github.com/gobuffalo/toodo/blob/master/actions/todos.go

**Comment by as27** [comment]
Inside the documentation it is not defined how to use the resources generator for longer named models.

For one word models that is clear, but whats with longer model names. For example a model `ContentSection`. 

How should the user generate that resource?

```
buffalo g r content_sections
buffalo g r contentSections
buffalo g r ContentSections
```

or should the generator support all possibilities?

**Comment by markbates** [comment]
I would think it should be able to support any of those possibilities.

**Comment by as27** [comment]
I am moving forward. Now I need feedback, because I am not sure if I am on the right track. The following file is completely generated via `buffalo g r pages`:
[Link to the gist: pages.go](https://gist.github.com/as27/c5bf31a0f3e8faef71044d44ee870028)

Not all functions are completed so the status is WIP. The code compiles and works, when the template files exist.

I added some comments to make that code easier to edit. Is this too much? or should there be much more comments? 

Something different: I don't know how to solve this:
In line 32 the path is in [] brackets:
`// Show gets the data for one page. This function is mapped to the path GET /pages/[page_id]`

That is because inside the template following does not work
```
GET /{{under}}/{{{singular}}_id} <-- causes an error
GET /{{under}}/\{{{singular}}_id} <-- renders as GET /pages/{{{singular}}_id}
```

**Comment by markbates** [comment]
Wow! This is looking really good so far! Very impressed!

To answer the last question first, you need to escape the `{{` otherwise Go templates tries to execute it. Here's an example of how to escape it:

https://github.com/markbates/pop/blob/master/soda%2Fcmd%2Fgenerate%2Fconfig_templates.go#L12

It's ugly, but that's just how you do it. :(

I'm all for comments in the generated code, the more the merrier!

The only comment I'll make at this stage (knowing that this is WIP), is to use the model name as the variable name.

Right now you have this:

```go
t := &models.Page{}
```

I would make it:

```go
page := &models.Page{}
```

In addition to generating the corresponding tests, I would generate, at the very least "stub" HTML pages for each action. If you want to get really crazy you can implement the form pages using https://github.com/gobuffalo/tags, but it would be enough to start with just having simple HTML pages like:

```html
<h1>Pages#Show</h1>

Find me in templates/pages/show.html
```
