### ISSUE TITLE
Add Live Reload Support

### ISSUE THREAD

**Issue by corylanou** [gobuffalo/buffalo#510]
It would be nice to add a live-reload support option to the "buffalo dev" command for faster development.

**Comment by cayter** [comment]
The doc [here](https://gobuffalo.io/docs/getting-started#running-in-dev) says it's supported. However, when using it with golang 1.9.0, it doesn't live reload when there's file changed. Not sure if this is a bug.

**Comment by markbates** [comment]
You're confusing live reload, which auto refreshes a web page, which Buffalo doesn't support (yet), with auto rebuilding of the Go binary, which it does support.

-----------
Mark Bates

**Comment by cayter** [comment]
Yep, I got confused because I was using `buffalo dev` in docker container with Dinghy over NFS and the code rebuild didn't work. However, after 20+ mins digging into the code, have noticed that `refresh` package uses `fsnotify` which doesn't support NFS sync yet. Am currently using gin reload utility to workaround it. Thanks though!

**Comment by markbates** [comment]
Wow! That's a crazy set up! :) Would you mind opening a ticket describing the problem and your work around so we can add it to the troubleshooting guide? Maybe save someone else a bit of time in the future.

-----------
Mark Bates

**Comment by cayter** [comment]
Here you go. https://github.com/gobuffalo/buffalo/issues/620

**Comment by markbates** [comment]
Awesome. Thanks!

-----------
Mark Bates

**Comment by paganotoni** [comment]
@markbates should we work on this (js/css) live reload functionallity, i could look into it after i send asset fingerprinting PR again

**Comment by markbates** [comment]
Definitely. I think the way to do this is to grow `refresh` a little bit and have it expose a channel that can be listened to for events that come out of it. then the `buffalo dev` command can listen to those events and send a live reload message. it would probably only work with `webpack` since there isn't a good Go based solution.

**Comment by forrest321** [comment]
With webpack now in place, it looks like this one can be closed.

**Comment by paganotoni** [comment]
covered with #1027 until we grow refresh :)
