### ISSUE TITLE
running db create and db seed and db migrate on server without go

### ISSUE THREAD

**Issue by u007** [gobuffalo/buffalo#607]
Hi,

how do we do this?
do we need to cross compile soda for linux and upload soda to server?

thanks

**Comment by markbates** [comment]
If you have a binary you built with `buffalo build` then you can run grift tasks as well as migrations from that binary, see: [https://gobuffalo.io/docs/building#binary-commands](https://gobuffalo.io/docs/building#binary-commands). You can't create a db from the binary.

In theory your production DB would probably be set up already, which is why those commands aren't included. If it's not already setup, you could either compile and push the `buffalo` binary, or compile and push `soda`.

**Comment by u007** [comment]
i got soda working :) thanks
