### ISSUE TITLE
Duplicate Session Set-Cookie Header

### ISSUE THREAD

**Issue by sbry** [gobuffalo/buffalo#631]
Setting up file-based session data I found that my development-server was sending duplicate session-cookie header-lines, and I did not find out why yet:

```
$ curl -sD - -o /dev/null http://localhost:3000 # return headers of a GET-request
HTTP/1.1 200 OK
Content-Type: text/html
Set-Cookie: app1_de_session=MTUwNDAzODI3MHxOd3dBTkRaUldVOVhSVTlhTWpaS05GQmFVMHhLU0VnM1NrMU1XRU5QUTFsWk1rcFROa1pJUVVzeU0xSXpXVmRYV1VsTVZGRlBWRUU9fJkTsUJhZBgUXAvmUN9ilqohj1DW6b1cvG9Bqs1YDcia; Path=/; Expires=Thu, 28 Sep 2017 20:24:30 GMT; Max-Age=2592000
Set-Cookie: app1_de_session=MTUwNDAzODI3MHxOd3dBTkRaUldVOVhSVTlhTWpaS05GQmFVMHhLU0VnM1NrMU1XRU5QUTFsWk1rcFROa1pJUVVzeU0xSXpXVmRYV1VsTVZGRlBWRUU9fJkTsUJhZBgUXAvmUN9ilqohj1DW6b1cvG9Bqs1YDcia; Path=/; Expires=Thu, 28 Sep 2017 20:24:30 GMT; Max-Age=2592000
Date: Tue, 29 Aug 2017 20:24:30 GMT
Transfer-Encoding: chunked
```

Later I remembered that gophercon.com was running on buffalo as well and there are duplicate session cookies set as well (the last one prevails I guess):

```
$ curl -sD - -o /dev/null https://www.gophercon.com/about/contact
HTTP/1.1 200 OK
Content-Type: text/html
Date: Tue, 29 Aug 2017 20:17:53 GMT
Server: Caddy
Set-Cookie: _buffalo_session=MTUwNDAzNzg3M3xEdi1CQkFFQ180SUFBUkFCRUFBQU1QLUNBQUVHYzNSeWFXNW5EQTRBREhKbGNYVmxjM1J2Y2w5cFpBWnpkSEpwYm1jTURBQUtOVFl6TkRZeU5XUTBOdz09fA9D6By1cx9PiEbufDSm72NxEl5-dyOzFHq53yVpp58J; Path=/; Expires=Thu, 28 Sep 2017 20:17:53 GMT; Max-Age=2592000
Set-Cookie: _buffalo_session=MTUwNDAzNzg3M3xEdi1CQkFFQ180SUFBUkFCRUFBQVVQLUNBQUlHYzNSeWFXNW5EQTRBREhKbGNYVmxjM1J2Y2w5cFpBWnpkSEpwYm1jTURBQUtOVFl6TkRZeU5XUTBOd1p6ZEhKcGJtY01DUUFIWDJac1lYTm9Yd2RiWFhWcGJuUTRDZ1FBQW50OXyJc4pDCo0WA0jYHuG-1Rb5Ik4GuoeYKnRm4V20Wxb27Q==; Path=/; Expires=Thu, 28 Sep 2017 20:17:53 GMT; Max-Age=2592000
Transfer-Encoding: chunked

```

Am I missing something?

**Comment by markbates** [comment]
It's most likely from repeated calls to save the session. We use the http://www.gorillatoolkit.org/pkg/sessions package under the covers, so it could be an issue there, maybe. my gut says it's multiple save calls.

Looking at it, ultimately it goes down to `http.SetCookie` which uses `Add` instead of `Set`, which is why, if you call it multiple times, you get multiple calls. 

https://golang.org/src/net/http/cookie.go?s=3118:3166#L122

Not sure there's really anyway to avoid to that, short of writing our own implementation of sessions and cookie handling, which I'm not too keen to do. :)

After doing some quick googling, it appears that it's not an issue, and it is often typical to set many `Set-Cookie` headers like that. https://tools.ietf.org/html/rfc6265#section-3

Are you experience a problem or weirdness? Or are you merely curious? This doesn't seem like a bug, so I'm going to close it out. However, if you're seeing an issue, please re-open with details of the problem you're running into.

**Comment by leodotcloud** [comment]
I ran into similar issue where I was seeing multiple/duplicate session cookies with the same name. Finally after debugging figured out I had to use CORS settings as I was using a different backend.

Frontend: localhost:4200
Backend: localhost:3000

Backend config:
```
if app.Env == "development" {
			c := cors.New(cors.Options{
				AllowedOrigins:   []string{"http://localhost:4200"},
				AllowCredentials: true,
			})
			app.PreWares = append(app.PreWares, c.Handler)
		}
```

Frontend config:
```
export default DS.JSONAPIAdapter.extend({
  host: ENV.backend,
  namespace: 'v1-beta',
  ajax(url, method, hash) {
    if (ENV.APP.usingCors) {
      if (hash === undefined) { hash = {}; }

      hash.crossDomain = true;

      if (ENV.APP.corsWithCreds) {
        hash.xhrFields = { withCredentials: true };
      }
    }
    return this._super(url, method, hash);
  },
});
```
