### ISSUE TITLE
Any simple way to use custom layout?

### ISSUE THREAD

**Issue by nyrf** [gobuffalo/buffalo#640]
I want to use `admin.html` to admin area, now i must use `r.HTML("index.html", "admin.html")` in every action,  is there a simple way to set layout for router group? thank.

**Comment by sio4** [comment]
For my case, I do not use separated layout for admin but using specific theme, style sheet. because for me, I use same layout for all but sometimes include some special buttons, divs, and colors.

For special block and buttons,  I use `<%= if (admin) {  %>...htmls...<% } %>` or something similar.
And for theme, just set a context variable on the middleware for admin page handler(originally for protecting special pages or group of route, but finally set `c.Set("theme", "admin_black")` ) and include `<link href=".../<%= theme %>/...>` in `application.html`.

Just for my cases but I hope it help you.

**Comment by paganotoni** [comment]
You can do the following on your action:

return c.Render( 200, r.HTML(“your template.html”, “yourothertemplate.html”))

AP

-----------------------------
Antonio Pagano

@apaganobeleno
http://wawand.co

**Comment by sio4** [comment]
@paganotoni Question owner already mentioned that. But as I understand, what he want to do is to prevent doing it for all admin pages. or at least on group of route. I think it is better if there is a context variable to override `e.HTMLLayout`.

**Comment by paganotoni** [comment]
Oh sorry, I didn’t read the entire thread, You could always add a middleware for that group.

**Comment by sio4** [comment]
No problem. Anyway I satisfied with my current approach but sometime it may
helps others if there is context variable :-)

-- 
"the love you take is equal to the love you make." - the end, by beatles

2017. 9. 18. 오후 8:37에 "Antonio Pagano" <notifications@github.com>님이 작성:

**Comment by markbates** [comment]
Another option is to create a second Render engine in actions/render.go and then use that one in your admin actions instead of the other Render engine.

-----------
Mark Bates

**Comment by nyrf** [comment]
@sio4 Thanks, looks like this is the only way now.

**Comment by nyrf** [comment]
@markbates Thanks, i tried and it works also.

**Comment by nyrf** [comment]
Thanks, I found i can use a middleware

```go
func SetLayout(next buffalo.Handler) buffalo.Handler {
	return func(c buffalo.Context) error {
		layout := "application.html"
		if strings.Contains(c.Request().RequestURI, "/admin") {
			layout = "admin.html"
		}
		r.HTMLLayout = layout
		return next(c)
	}
}


app.Use(SetLayout)
```

**Comment by markbates** [comment]
I wouldn't do that. You're essentially overriding a global value on each request. That means that it's possible for two requests to come in at the same time and one would have the wrong template.

-----------
Mark Bates

**Comment by nyrf** [comment]
@markbates I see, thanks, i'll glad to see  `buffalo` can set layout.
