### ISSUE TITLE
assets `public` path still embedded into the binary with -e flag ?

### ISSUE THREAD

**Issue by sapiens-sapide** [gobuffalo/buffalo#741]
Hi all,
I've build a very simple app with default assets (buffalo 0.9.5). When I build the app with the `-e` flag (`buffalo build -e`), the binary is created along side with the assets.zip file.  
If I delete the assets.zip file then launch the application, all assets are still served by the app ! It should trigger 404 for images, css…, shouldn't it ?

[edit]
If I delete all stuffs within `$GOPATH/src/my_repo/public`, the binary can't find assets anymore… Even if I unzip assets.zip to the same directory than the binary. Does it means that `$GOPATH/src/my_repo/` is hardcoded into the final binary ?

**Comment by markbates** [comment]
This is expected behavior. The way things work is it first checks for the files in memory (i.e. built into the binary), if they can't be found there, it looks to disk to find the files (i.e. when you're developing).

In order to reliably locate the files it uses the path of your app to look for the files, so yes, the path is coded in there, because it has to be.

**Comment by stanislas-m** [comment]
@markbates The [documentation](https://gobuffalo.io/docs/building) on gobuffalo.io states: "Please note this will disable the internal assets handling too, so the final executable is lighter."

Since it's not the case, we need to fix the documentation.

**Comment by sapiens-sapide** [comment]
Or may be the path that is still embedded into the final executable should be a relative path instead of the complete path to the repo.
