### ISSUE TITLE
running `buffalo build` with `-o` flag deletes working directory 

### ISSUE THREAD

**Issue by sapiens-sapide** [gobuffalo/buffalo#827]
I ran `buffalo build` to build my app and everything worked fine. But, when I ran `buffalo build -o custom_binary_name` the command failed with a `……/……/main.go: no such file or directory` and my working directory has been completed erased !  

Buffalo version is: v0.10.2. 

Issue encountered on mac osx and freebsd.

**Comment by markbates** [comment]
Well, it definitely shouldn’t do that. Yikes.

The problem is it clears out the build directory, which is also your working directory at that point. Obviously it shouldn’t do that if you specify the working directory.

The work around is to do something like `-o bin/custom-name`

-----------
Mark Bates

**Comment by sapiens-sapide** [comment]
Thanks for your reply. It should have a safeguard to prevent this unexpected behaviour.
