### ISSUE TITLE
Allow go test to work as expected

### ISSUE THREAD

**Issue by TankTheFrank** [gobuffalo/buffalo#922]
Running with "buffalo test" or "GO_ENV=test go test ./..." everything is fine, however running "go test ./..." fails with CSRF errors. Given that virtually every tool/editors/ci/whatever is using "the go way" having to add an environment variable or a custom command to run tests is rather cumbersome.

I'm using a freshly generated template with a simple ActionSuite post test on buffalo 0.10.3 with suite 1.0.0.

**Comment by markbates** [comment]
This is a no fix I’m afraid. You’re also running  tests against the development database, without the env flag. Buffalo test also sets up and tears down things like the test database. There’s no getting around it. Unless there’s some secret thing, which there might be, that lets you know programmatically that you’re running tests. This will remain this way for now.

**Comment by TankTheFrank** [comment]
A quick google search come up with this stackoverflow question

https://stackoverflow.com/questions/14249217/how-do-i-know-im-running-within-go-test

I get it that the framework is targeting the rails converts but cutting out the golang workflow when it can be helped is a questionable decision.

**Comment by TankTheFrank** [comment]
@markbates FYI that solution does seem to work, changing models.go to this

```
func init() {
	// Detect test mode
	if flag.Lookup("test.v") != nil {
		envy.Set("GO_ENV", "test")
	}

	var err error
	env := envy.Get("GO_ENV", "development")
        ....
```
makes "go test ./..." behave as "GO_ENV=test go test ./..."

This is obviously a poc and not a working solution, I'm not familiar enough with the internals of the framework and how the test mode affects everything to provide a real solution, just pointing out that it wouldn't be too hard to fix.

**Comment by markbates** [comment]
Thanks for finding that! I've re-opened the issue since, as I said, if there was a way to do it, we would. This will, at least, allow `go test` to behave as you would expect, although you won't get any of the benefits of `buffalo test`, but that might be ok for some people.

On a side note, if you could try and keep the conversation a bit more civil, that would be fantastic. Comments such as "cutting out the golang workflow when it can be helped is a questionable decision." can come across as a bit agressive. We try to keep this project friendly and helpful. Thanks.

If you would like to take a crack at a PR for this, that would be very welcome. It would be great to have it in the next release.

**Comment by TankTheFrank** [comment]
I stand by my previous statement despite your ad-hominem attack, not fixing "go test" when it can be fixed and forcing the use of an alternate syntax it is a questionable decision. From where I stand closing the ticket immediately with "will not fix" especially when the solution was so easy to find spells a voluntary decision of ignoring the standards. Given that the ticket is opened again I assume we both finally agree that "go test" is better off fixed than broken and ignored.

Missing the benefits of "buffalo test" but still working is exactly the point I'm trying to get across. I never said that I expect "go test" to replace "buffalo test" nor to be interchangeable, on the contrary, I'd argue that they complement each other and each has its own merits. I'll provide two simple use cases as to why the framework should work without working against me by being "too opinionated":

1. Every editor has "run test at cursor" or run "tests from this file". In this case the test should run fast without any assumptions about database management. As it is, it works out of the box as long as a the crsf token doesn't come into play.

2. CI integration with a buffalo app as "part of a larger project" - otherwise it doesn't really matter if "go test" is replaced with "buffalo test". Say for instance a grpc microservice as the main piece that also needs a small embedded website to provide stats and whatnot for admins. In this case it makes sense to have a single set of tests and not have the database nuked in the middle of it.

About the PR - is it really worth adding " || flag.Lookup("test.v") != nil" on this line a pr? This should fix the csrf issue itself even when running "GO_ENV=_whatever_ go test" - which should be the expected behavior imo.

https://github.com/gobuffalo/buffalo/blob/7aaaee030c62e0e8e2c0023065acd4cf00ab2a9f/middleware/csrf/csrf.go#L54

I'm all for friendliness as long as honest and constructive feedback is allowed - I have no interest in an echo chamber. 

As an aside, pointing out that a decision might be not ideal is what passes as "rude and aggressive" these days?

**Comment by markbates** [comment]
Please understand I’m not attacking you. I’m all for open and constructive feedback, ask anyone who knows me and this project. Several people reached out to me privately and felt your tone was aggressive. That’s all I was trying to saying. 

In my original message, I wrote while walking through an airport on vacation with my family, explained why it was that way and said if there was a way to make it happen, we would. You found a way, and so the ticket was reopened. 

Your last comments are definitely, as you said, aggressive. I am now feeling personally attacked for my “questionable” decisions. I agree that being able to run go test stand-alone is beneficial. Why wouldn’t I? This is project run by myself and others in our spare time as a labor of love. We don’t have all the answers. We don’t have time to research every option, idea, etc... 

And, in case you’re curious as why we ended up with an ENV variable, it’s because a year ago when I asked several members of the Go team, how to approach this exact problem, using either an env variable or build tags was their solution. So please bear in mind that there is history here before judging myself or anyone else here. 

With that said, can we please start off again on the right foot?

**Comment by matryer** [comment]
Would this work?

In `thing.go`:

```
package thing

var testMode = false
```

And in `thing_test.go`:

```
package thing

func init() {
    testMode = true
}
```

**Comment by RedPh0enix** [comment]
Please forgive me for contributing little to either the conversation, or the fix, but the solution offered above (changing models.go to look for test.v in flags) is an easy modification for anyone who uses atom/go-plus with the 'run tests on save' feature enabled.

Unfortunately, while the go-plus configuration allows you to change the arguments you can supply to go test, there doesn't seem to be a simple way of prepending an env change.

It took me a while to work out that my test_blah.go functions would be operating on my test DB, whilst anything called from something like: res := as.HTML("/blah").Get(), would be operating on my development DB; this would generally result in pushing a valid user into my test DB to avoid authentication checks, then wondering why there seemed to be no users in the DB when I hit the associated action after the .Get call. The models.go modification sorts that out nicely.

Hopefully this comment contains enough google-fodder to allow others who are experiencing the problem to find the issue; I struggled for several hours.

I'll reiterate the solution here, to save everyone needing to claw their way through the thread above:

In your models/models.go file, add the following code (in bold):
```
func init() {
	**// Detect test mode
	if flag.Lookup("test.v") != nil {
		envy.Set("GO_ENV", "test")
	}**

	var err error
	env := envy.Get("GO_ENV", "development")
        ....
```
