### ISSUE TITLE
Creating a Caddyfile

### ISSUE THREAD

**Issue by kteb** [gobuffalo/buffalo#971]
Following few questions on Caddy on the Buffalo slackchannel, @markbates thought that it could be nice to have a Caddyfile generated for the buff app. 

The goal is to have the dev env providing https connection locally with a self generated certificate. 

I tested a file locally and it worked well, I created this ticked to discuss few details of the implementation.

* Should it be a plugin or a default feature when we do buffalo new ? 
* On which port should be listen for the https connection ? 
* For me it's clear that caddy proxy to the 3000 port as it's the default buffalo port. 
* Should we think a bit more, to have a way to try to start Caddy when we do `Buffalo dev` ?
* I guess a flag skip-caddy (if it's not a plugin) ?

**Comment by markbates** [comment]
I would say start with a plugin. That way it's easier to iterate on, since it's not part of the Buffalo release schedule. Then, if it works well, and there's a demand for it, we can move into Buffalo core.

To answer some of the questions:

* Port - I would default to `3000`, but accept the `PORT` env. You could also prompt the user during the `buffalo g caddy` step and ask them what port to use, with `3000` being the default.
* HTTPS Port - I would say Caddy should start on `80`/`443` and forward requests to the above port, `3000`. You'll probably also need to prompt for the users email address for TLS let's encrypt stuff. Don't quote me on that since I'm not that experienced with Caddy.
* Add a `buffalo dev caddy` command, via the plugin, that starts Caddy and `buffalo dev`. 

I think that's it for my ideas. :)

**Comment by kteb** [comment]
You can't ask let's encrypt to sign a localhost certificate. 

https://letsencrypt.org/docs/certificates-for-localhost/ 

But caddy manage to generate himself a self-signed certificate. So the certificate will have to be added as an exception to the browser. 

Good exercise for a first plugin 😃

**Comment by kteb** [comment]
A first alpha verison is available: 

https://github.com/kteb/buffalo-caddy

It doesn't manage to download caddy for now (the compilation of caddy needs a little bit more that just download the package).

I've tested the solution on linux but I needed to 

use either setcap (`setcap 'cap_net_bind_service=+ep' /path/to/caddy`)

or authbin to be able to serve port 80 and 443 without being root.

**Comment by stanislas-m** [comment]
@kteb I'm closing this issue since it's quite old and you already provided a solution. Please feel free to add some words about your plugin in the documentation, probably in the deployment section. :)
