### ISSUE TITLE
Commit Gopkg.lock and remove vendored blackfriday

### ISSUE THREAD

**Issue by dlsniper** [gobuffalo/buffalo#973]
Hi,

Following up the discussion on Slack, here's a couple of things that I've noticed that need to be addressed before I can contribute to buffalo:

- https://github.com/gobuffalo/buffalo/tree/master/vendor/github.com/russross/blackfriday -> this is the only committed dependency. Is there any reason for this to be committed?
- ` Gopkg.lock ` is not committed so my version of the dependencies might be different than someone else's version.

Thank you.

**Comment by markbates** [comment]
@dlsniper yeah, there was a reason why that one particular package is vendored. They made a v2 branch and left master at 1x. Another package updated to use v2 of bf, but since go get pulls master everything breaks. Hence the vendor of the v2 package.

**Comment by markbates** [comment]
PR: https://github.com/gobuffalo/buffalo/pull/975

**Comment by markbates** [comment]
So I woke this morning and had more clarity on why this is, and why I'm closing this issue, unless of course, after hearing my reasons, you have a better idea, I'm all ears.

There's a lot at work here, and these decisions weren't made arbitrarily, but are rather the result of over a years worth of trying to get the right combo that works in all situations.

Buffalo is both an import-able package and a binary, which means we need to be able to serve both beasts. Typically in a package you don't vendor and in a binary you do. So which to choose for Buffalo.

First we need to take into account the basic `go get` way of installing Buffalo. Vendoring dependencies here works well, in fact it's a great solution, however there are some issues around SQLite now being opt-in, that could cause problems there. However, if Buffalo vendor all it's dependencies and your app **also** vendored dependencies then you can run into the stupid vendoring error of `buffalo/vendor/type` does not match `myapp/vendor/type`. So in order to allow people to vendor their dependencies, Buffalo doesn't vendor it's dependencies. 

Which leads us to why blackfriday is vendored, and nothing else is. The BF library, used a `v2` branch when they decided to cut a v2. The GitHub_flavored_markdown package updated it's `master` branch to use the `v2` branch of BF. Since `go get` always pulls from `master` GHM breaks, so we vendor the `v2` branch of BF to fix that problem. Of course if someone tries to import BF into their app, we run into that vendoring issue we talked about earlier.

And finally the `Gopkg.lock` file was ignored because Dep was trying to use it to resolve dependencies when using Dep with an app, which meant end users weren't able to control the versions of some of their dependencies, which caused a lot of problems.

So there you have it, a condensed version of over a years worth of trying to make everyone, and every tool, happy.

Hopefully that answers those questions. :)
