### ISSUE TITLE
Proposal: Live asset reloader 

### ISSUE THREAD

**Issue by jaynagpaul** [gobuffalo/buffalo#997]
One of my favorite things from Phoenix framework is the [live asset reloader](https://github.com/phoenixframework/phoenix_live_reload). It would be great to have a live asset reloader during development. Here's the description of what it does taken straight from the readme.

> this project adds a plug which injects some JavaScript into your page with a WebSocket connection to the server. When you make a change to anything in your config for live_reload (JavaScript, stylesheets, templates, and views by default) then the page will be reloaded in response to a message sent via the WebSocket. If the change was to an Elixir file then it will be recompiled and served when the page is reloaded. If it is JavaScript or CSS, then only assets are reloaded, without triggering a full page load.

Wanted Features:
- Recompile templates
- Watch javascript / CSS and send a message via websocket to reload

I may attempt to implement this myself in the future.

**Comment by JacobSoderblom** [comment]
My suggestion is to use [webpack-dev-server](https://webpack.js.org/configuration/dev-server/) on the `buffalo dev` command and  [write-file-webpack-plugin](https://github.com/gajus/write-file-webpack-plugin) as a plugin to `webpack config`.

Due to `webpack-dev-server` store the files in the memory and serve them through a node server, we will have to change how `buffalo` handle the assets. But if we use `write-file-webpack-plugin` we will be able to use the assets as they are today.

This will solve the _Watch javascript / CSS and send a message via websocket to reload_ feature.

There might be better ways to solve this, but I don't know if there are any easier ways.

**Comment by markbates** [comment]
@JacobSoderblom I'd love to see a PR, would you be interested in taking a crack at it?

**Comment by paganotoni** [comment]
Covered by #1027
